name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run build-storybook --workspace storybook-app
    - run: npm i -g gh-pages
    - run: git config user.name github-action
    - run: git config user.email github-actions@github.com
    - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - run: npx gh-pages -d dist/